spring.application.name=dio-spring-ai-budget
spring.datasource.url=jdbc:h2:mem:budgetdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Configuração da Chave da OpenAI (o usuário vai colocar a própria)
spring.ai.openai.api-key=${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}
spring.ai.openai.chat.options.model=gpt-4o-mini